### ISSUE TITLE
No module named 'cudf'

### ISSUE THREAD

**Issue by pyagoubi** [rapidsai-community/rapidsai-csp-utils#67] opened 2022-12-03 12:57 UTC
After running the install script on colab and then

import cudf

I get:
ModuleNotFoundError Traceback (most recent call last)
in
----> 1 import cudf

ModuleNotFoundError: No module named 'cudf'

**Comment by adalovelace** [comment] 2023-03-01 14:44
I ran into the same problem. The issue is in the `rapidsai-csp-utils/colab/pip-install.py` script which throws this error:

```
Traceback (most recent call last):
  File "rapidsai-csp-utils/colab/pip-install.py", line 26, in <module>
    gpu_name = pynvml.nvmlDeviceGetName(pynvml.nvmlDeviceGetHandleByIndex(0)).decode('UTF-8')
AttributeError: 'str' object has no attribute 'decode'
```

In turn, cudf is not installed and later you get the "No module named 'cudf'" error. 

To fix this I copied the source code into a new cell in Colab notebooks and simply removed the decode part from this line https://github.com/rapidsai-community/rapidsai-csp-utils/blob/main/colab/pip-install.py#L26.

Doing this should work and you'll be able to successfully install cudf. You can check it worked by running `import cudf` in a new cell.

Hope it helped!

**Comment by taureandyernv** [comment] 2023-04-06 20:40
closed by #76

**Closed by taureandyernv** 2023-04-06 20:40 UTC

**Comment by kelemenantal** [comment] 2023-04-07 12:40
Unfortunately it is still doesnt work for me and getting the same error which:  No module named 'cudf'

I think I did everything rigth... Any other tips, why doesnt it work properly?

**Comment by taureandyernv** [comment] 2023-04-07 19:06
Hey @kelemenantal , i tested it on a fresh copy of the template notebook and it worked.  [Have you tried the most recent template?  You can always find them on our website](https://rapids.ai/#quick-start).  LMK.  I'll leave the closed as it is solved, but we can debug.  Also, we can chat on the RPAIDS slack.

**Comment by kelemenantal** [comment] 2023-04-08 10:24
> Hey @kelemenantal , i tested it on a fresh copy of the template notebook and it worked. [Have you tried the most recent template? You can always find them on our website](https://rapids.ai/#quick-start). LMK. I'll leave the closed as it is solved, but we can debug. Also, we can chat on the RAPIDS slack.

Thx a lot, it is working with the template you shared! I have further issues, but it has no contact with the [No module named 'cudf'] so lets leave the case closed.
