### ISSUE TITLE
Can't import cupy

### ISSUE THREAD

**Issue by Bughehehe** [rapidsai-community/rapidsai-csp-utils#93] opened 2023-12-30 16:25 UTC
After installing all thing from colab template this error occures while im trying to import cupy

ImportError                               Traceback (most recent call last)
[/usr/local/lib/python3.10/site-packages/cupy/__init__.py](https://localhost:8080/#) in <module>
     16 try:
---> 17     from cupy import _core  # NOQA
     18 except ImportError as exc:

4 frames
[/usr/local/lib/python3.10/site-packages/cupy/_core/__init__.py](https://localhost:8080/#) in <module>
      2 
----> 3 from cupy._core import core  # NOQA
      4 from cupy._core import fusion  # NOQA

cupy/_core/core.pyx in init cupy._core.core()

[/usr/local/lib/python3.10/site-packages/cupy/cuda/__init__.py](https://localhost:8080/#) in <module>
      7 from cupy._environment import get_hipcc_path  # NOQA
----> 8 from cupy.cuda import compiler  # NOQA
      9 from cupy.cuda import device  # NOQA

[/usr/local/lib/python3.10/site-packages/cupy/cuda/compiler.py](https://localhost:8080/#) in <module>
     12 
---> 13 from cupy.cuda import device
     14 from cupy.cuda import function

cupy/cuda/device.pyx in init cupy.cuda.device()

ImportError: cannot import name syncdetect

The above exception was the direct cause of the following exception:

ImportError                               Traceback (most recent call last)
[<ipython-input-15-5c5674e0dd22>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import cupy, cuml, cugraph, cuspatial

[/usr/local/lib/python3.10/site-packages/cupy/__init__.py](https://localhost:8080/#) in <module>
     17     from cupy import _core  # NOQA
     18 except ImportError as exc:
---> 19     raise ImportError(f'''
     20 ================================================================
     21 {_environment._diagnose_import_error()}

ImportError: 
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: cannot import name syncdetect
================================================================

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by beckernick** [comment] 2024-01-03 17:23
@Bughehehe I'm not able to reproduce this in a fresh Colab environment -- this may now be resolved. Can you confirm whether you still experience this issue?

**Comment by taureandyernv** [comment] 2024-05-15 11:29
closing due to no reply.  @Bughehehe , if this happens again, please reopen

**Closed by taureandyernv** 2024-05-15 11:29 UTC
